x-node: &node
  build:
    dockerfile: ./target-node/Dockerfile
    context: .
  privileged: true
  tty: true
  networks:
    - mynet
  extra_hosts:
    - "ntp:10.0.1.40"

services:
  ntp:
    image: dockurr/chrony
    container_name: ntp
    environment:
      NTP_SERVERS: "time.cloudflare.com"
      ENABLE_SYSCLK: "true"
    ports:
      - 123:123/udp
    cap_add:
      - SYS_TIME
    networks:
      mynet:
        ipv4_address: 10.0.1.40
  
  ansible:
    container_name: ansible
    hostname: ansible
    ports:
      - '8990:8999'
    depends_on:
      - node01
      - node02
    build:
      dockerfile: ./control-node/Dockerfile
      context: .
      args:
        WS_PORT: 8990
    tty: true
    volumes:
      - ./work:/app/work
    networks:
      mynet:
        ipv4_address: 10.0.0.40
    extra_hosts:
      - "ntp:10.0.1.40"

  node01:
    <<: *node
    hostname: node01
    container_name: node01
    ports:
      - '8001:80'
      - '2201:22'

  node02:
    <<: *node
    hostname: node02
    container_name: node02
    ports:
      - '8002:80'
      - '2202:22'

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
