x-node: &node
  build:
    dockerfile: ./target-node/Dockerfile
    context: .
  privileged: true
  tty: true
  networks:
    - mynet

services:
  ansible:
    container_name: ansible
    hostname: ansible
    depends_on:
      - node01
      - node02
    build: ./control-node
    tty: true
    working_dir: /root/work
    volumes:
      - ./work:/root/work
    networks:
      - mynet

  node01:
    <<: *node
    hostname: node01
    container_name: node01
    ports:
      - '8001:80'
      - '2201:22'
      - '8991:8999'
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "22"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - mynet

  node02:
    <<: *node
    hostname: node02
    container_name: node02
    ports:
      - '8002:80'
      - '2202:22'
      - '8992:8999'
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "22"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
