x-node: &node
  build: ./target-node
  privileged: true
  tty: true
  networks:
    - mynet

services:
  ansible:
    container_name: ansible
    hostname: ansible
    depends_on:
      - node01
      - node02
    build: ./control-node
    tty: true
    working_dir: /root/work
    volumes:
      - ./work:/root/work
    networks:
      - mynet

  node01:
    <<: *node
    hostname: node01
    container_name: node01
    ports:
      - '8101:80'
      - '2201:22'
      - '8991:8999'
    networks:
      - mynet

  node02:
    <<: *node
    hostname: node02
    container_name: node02
    ports:
      - '8102:80'
      - '2202:22'
      - '8992:8999'
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
